### ISSUE TITLE
After installing v0.6.4, changes to configuration page causes HA lockup

### ISSUE THREAD

**Issue by sdholden28** [agittins/bermuda#185]
## Version of the custom_component
v0.6.4

## Configuration
![image](https://github.com/agittins/bermuda/assets/97199106/ebd7769c-0fff-4347-8fac-d120e6bd5e40)

## Describe the bug
After upgrading to v0.6.4, making ANY changes on the configuration page of Bermuda results in a full HA frontend crash. Once this happens, I can only access the HA instance via SSH and must issue a reboot command before normal functionality is restored. This is repeatable. I have reinstalled the integration with no change. I have not yet downgraded to v0.6.3, but that will be my next step to see if the issue persists.

## Debug log
I'm uncertain on the best way to grab logs here. Once the issue occurs, I don't seem to be able to get any logs, and they're gone after the SSH reboot. Happy to provide them if you have any instruction or suggestions.

**Comment by agittins** [comment]
Yikes!

What version of HA are you running? My dev machine running 2024.4.0 doesn't do it, but my production machine running 2024.5.2 does.

Since I can replicate the issue I should be able to work out the fix given enough brain cells. It's looking like the integration continually reloads in a loop while the frontend is left just spinning its wheels.

I'll need some sleep before tackling this, unfortunately. I'll pin the issue and post on the community thread so hopefully we can avoid others bumping into the issue.

**Comment by sdholden28** [comment]
I'm running HAOS on an an Intel Nuc. Bare metal.

Core: 2024.5.2
Supervisor: 2024.05.1
HAOS: 12.2

It threw me for quite a loop! I was like hmmm, this sure is taking a while, then HA was unavailable, so I restarted via SSH, and did it again. Ha. During the second reboot, my entire zigbee network went down. Turns out the system decided to assign my zigbee usb stick to a different logical port, for some strange reason. All sorted now, but it went to s@#t and back in a hurry. :)

**Comment by terryhonn** [comment]
Feeling invincible, I gave it a shot too.  

Same results as @sdholden28 , I'm running in a VM on Proxmox, had to reboot the VM in order to get stuff back.
HA OS 12.3
Core is 2024.5.2

**Comment by sdholden28** [comment]
I can confirm that rolling back to 0.6.3 resolves the issue.

*I've noticed one small thing that I believe is new. The integration page, at least on my system, doesn't show the version properly anymore. I assume this is just cosmetic and not related to the bug, but I think this just showed up in 0.6.4, and now remains for me after going back to 0.6.3. I could be wrong on that though. Anyway, just a heads up.
![image](https://github.com/agittins/bermuda/assets/97199106/f3fad990-b9f1-420b-9432-c50c1350044d)

**Comment by tbrasser** [comment]
Same here

**Comment by agittins** [comment]
> version number

Yes I noticed that, too. I suspect it's new for 2024.5.x and it's annoying because HACS seems to pull directly from git instead of using the generated release files, and i don't want to store the version of last release in HEAD because it would be a lie. I'll need to sus out how to adjust my workflow for that 😕

**Comment by adizanni** [comment]
Not sure it is related but there has been many changes related to thread safety in 2024.5.x causing some nasty loops in many custom integrations (ex https://github.com/Tasshack/dreame-vacuum/issues/523)

**Comment by agittins** [comment]
Yes, I am pretty certain that's what's going on - I made some changes to the (re)init routines to tidy up and remove warnings during reloads and stuff, and also made changes re the deprecation of some async job setups, but I think it pushed me into the path of whatever changes they've made for thread safety. I was looking at the dreame-vacuum issue last night in case it had any direct lessons for me, too :-)

Unfortunately my debugpy setup in vscode is a bit broken currently which will make it harder to track down, but I'm hoping I should be able to sort it out once I get some time later tonight.

**Comment by agittins** [comment]
Ok, I think I have this resolved, is anyone happy to give `main` a whirl before I create a new release?

In HACS, Bermuda, top-right-threedots-menu, Redownload, and choose "main" as the version. Download, then restart HA to test, and see if you can alter a config setting and submit it.

It was a one-line (bone-headed) fix and is working on my dev system and my home production, so hopefully that is the core solution, but let me know how you go!

**Comment by terryhonn** [comment]
Fix in main confirmed here. Thanks a lot!

**Comment by agittins** [comment]
Awesome, thanks! I'll do a release now.

**Comment by tbrasser** [comment]
Still having crashes here when adding devices to track. (also my LD2410 ble mmwave sensors stopped showing up)

**Comment by sdholden28** [comment]
I had a crash earlier this afternoon right after adding a new proxy via the
Shelly integration. I reloaded the Bermuda integration to pick up the new
proxy and HA crashed like yesterday. I need to setup a syslog server or
something like that to be able to capture info for this type of thing.

**Comment by agittins** [comment]
@tbrasser and @sdholden28 if you have ssh access to your machine and are running supervised, you can run
`docker logs -f --tail=80 homeassistant` which will show the last 80 lines of logs and keep showing future logs. Then if you can trigger the problem it should give you the output, at least until things wedge up 😰 

> also my LD2410 ble mmwave sensors stopped showing up

Is that in the configuration dialog, under "configured devices"? This might be a separate thing, but hard to say. If we can sort out these crashes and it's still happening after that feel free to raise an issue - I do have suspicions about that drop-down list being far from complete.

**Comment by agittins** [comment]
I've done a bit of an audit of any async calls being made and found at least one spot that might have been causing issues, I have pushed a fix for that to `main`.

If you're able to "redownload" and choose the `main` version I'd be interested if that solves it for anyone. It's working on my dev and production machines, but since I wasn't able to reproduce the issue I can't make any guarantees, yet :-)

**Comment by tbrasser** [comment]
No crashes so far (y), still seeing fewer devices than before though (before 6.3).

**Comment by agittins** [comment]
I'm going to close this now as I think we've probably got the key points covered.

@tbrasser I've just pushed to `main` some changes to how the device selection is done, it now uses Bermuda's internal cache of devices instead of the "current" set maintained by the bluetooth backend. I am filtering out "old" random macs but you should find it more comprehensive than previously. I've also changed the options flow to use sub-menus to allow for future additions to the config.
